### ISSUE TITLE
Error connecting to the service protocol

### ISSUE THREAD

**Issue by mdenoronha** [ChangeFinance/zendesk-flutter-plugin#27]
Trying to run a Flutter app with this installed results in the following error on Android device
`Error connecting to the service protocol: failed to connect to http://127.0.0.1:56576/0_hF6RVIb-M=/`

In pubspec.yaml: `zendesk_flutter_plugin: ^1.0.2`

Any help on this one?

**Comment by mdenoronha** [comment]
Other outcome is it'll install, run, immediately crash with no error message, staying on `Installing build/app/outputs/apk/app.apk`

**Comment by willyhystor** [comment]
has anyone get any solutions for this issue?

**Comment by hervinsen** [comment]
The validation registerWith method inside /android/src/main/java/com/getchange/zendesk_flutter_plugin/ZendeskFlutterPlugin.java 

will cause force close when run or debugging. 

To fix this you need to extend your main activity into flutter fragment activity. 

note: if you are using flutter embedded 2, you need to change :
* the import file inside ZendeskFlutterPluggin,java from 
import io.flutter.app.FlutterFragmentActivity;
into 
import io.flutter.embedding.android.FlutterFragmentActivity;
* Change your Android mainActivity to extend FlutterFragment Activity 

This lib using flutter fragment activity because it was needed from native zendesk-api-sdk

:) :)

**Comment by sudoFerraz** [comment]
Closing this as no updates were given, will be happy to reopen if there is any update or resolution.
